src/accounts/urls.py
from django.urls import re_path, path
from . import views

app_name = '_accounts'

urlpatterns = [
    re_path(r'^signup/$', views.signup_view, name='signup'),
]

src/articles/urls.py
from django.urls import re_path
from . import views

app_name = '_articles'

urlpatterns = [
    re_path(r'^$', views.article_list, name='list'),
    re_path(r'^(?P<slug>[\w-]+)/$', views.article_detail, name='detail')
]

src/djangonautic/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('accounts/', include('accounts.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/accounts/models.py
from django.db import models

# Create your models here.

src/articles/models.py
from django.db import models


class Article(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField()
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    thumb = models.ImageField(default='default.jpg',
                              blank=True,
                              upload_to='articles')

    # add in author

    def __str__(self):
        return self.title

    def snippet(self):
        return self.body[:50]

src/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class SignupForm(UserCreationForm):
    # def __init__(self, *args, **kwargs):
    #     super(SignupForm, self).__init__(*args, **kwargs)
    #     if self.errors:
    #         for f_name in self.fields:
    #             if f_name in self.errors:
    #                 classes = self.fields[f_name].widget.attrs.get(&#39;class&#39;, &#39;&#39;)
    #                 classes += &#39; errors&#39;
    #                 self.fields[f_name].widget.attrs[&#39;class&#39;] = classes
    #                 print(f_name)

    username = forms.CharField(widget=forms.TextInput(
        attrs={
            'class': 'form-control',
            'placeholder': 'Username'
        }))

    first_name = forms.CharField(
        label='First Name',
        max_length=30,
        required=False,
        help_text='Optional.',
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': 'first name'
        }))

    last_name = forms.CharField(
        label='Last Name',
        max_length=30,
        required=False,
        help_text='Optional.',
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': 'last name'
        }))

    email = forms.EmailField(
        label='Email',
        max_length=255,
        help_text='Required.',
        widget=forms.EmailInput(attrs={
            'class': 'form-control',
            'placeholder': 'valid email'
        }))

    password1 = forms.CharField(
        label='Password',
        widget=forms.PasswordInput(attrs={
            'class': 'form-control',
            'placeholder': 'Password'
        }))

    password2 = forms.CharField(
        label='Confirm Password',
        widget=forms.PasswordInput(attrs={
            'class': 'form-control',
            'placeholder': 'Password Again'
        }))

    class Meta:
        model = User
        fields = (
            'username',
            'first_name',
            'last_name',
            'email',
            'password1',
            'password2',
        )

    def clean_username(self):
        username = self.cleaned_data.get('username')
        try:
            user = User.objects.get(username=username)
        except:
            return username

        raise forms.ValidationError('username is already taken')

    # def clean(self):
    #     cleaned_data = super().clean()
    #     return cleaned_data

    def save(self, commit=True):
        user = super(SignupForm, self).save(commit=False)
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
        return user

src/accounts/views.py
from django.shortcuts import render, reverse
from .forms import SignupForm
from django.contrib.auth import login, authenticate
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.forms import UserCreationForm


def signup_view(request):
    if request.method == 'POST':
        # form = SignupForm(request.POST)
        signup_form = SignupForm(request.POST)
        if signup_form.is_valid():
            signup_form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)

            # return HttpResponseRedirect(reverse('_articles:list'))
        # signup_form = UserCreationForm()
        return render(request, 'accounts/signup.html',
                      {'signupForm': signup_form})

    else:
        signup_form = SignupForm()
        return render(request, 'accounts/signup.html',
                      {'signupForm': signup_form})

src/articles/views.py
from django.shortcuts import render
from .models import Article
from django.http import HttpResponse


def article_list(request):
    articles = Article.objects.all().order_by('date')
    return render(request, 'articles/article_list.html',
                  {"articles": articles})


def article_detail(request, slug):
    article = Article.objects.get(slug=slug)
    return render(request, 'articles/article_detail.html',
                  {"article": article})

src/accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% block body %}
<div class="container">
  <div class="row justify-content-center">
    <div class="col-xl-5 col-md-7 ">
      <h2>Signup Page</h2>
      <form action="{% url '_accounts:signup' %}" method="post">
        {% csrf_token %}

        <div class="form-group">
          <label for="{{signupForm.username.id_for_label}}">Username: *</label>
          {{ signupForm.username}}
          <div class="valid-feedback">
            Looks good!
          </div>
          {% if signupForm.username.errors%}
          <script>
            const username = document.querySelector('#id_username');
            username.classList.add('is-invalid')
          </script>
          {% endif %}
          <span class="">{{ signupForm.username.errors }}</span>
        </div>

        <div class="form-group">
          <label for="{{signupForm.first_name.id_for_label}}">First Name: </label>
          {{ signupForm.first_name }}
        </div>

        <div class="form-group">
          <label for="{{signupForm.last_name.id_for_label}}">Last Name: </label>
          {{ signupForm.last_name }}
        </div>

        <div class="form-group">
          <label for="{{signupForm.email.id_for_label}}">Email:* </label>
          {{ signupForm.email }}
          {% if signupForm.email.errors%}
          <script>
            const email = document.querySelector('#id_email');
            email.classList.add('is-invalid')
          </script>
          {% endif %}
          {{ signupForm.email.errors }}
        </div>

        <div class="form-group">
          <label for="{{signupForm.password1.id_for_label}}">Password:* </label>
          {{ signupForm.password1 }}
          {% if signupForm.password2.errors%}
          <script>
            const p1 = document.querySelector('#id_password1');
            p1.classList.add('is-invalid')
          </script>
          {% endif %}
          {{ signupForm.password1.errors }}
        </div>

        <div class="form-group">
          <label for="{{signupForm.password2.id_for_label}}">Confirm Password:* </label>
          {{ signupForm.password2 }}
          {% if signupForm.password2.errors%}
          <script>
            const p2 = document.querySelector('#id_password2');
            p2.classList.add('is-invalid')
          </script>
          {% endif %}
          {{ signupForm.password2.errors }}
        </div>

        <!-- {{signupForm.as_p}} -->
        <input type="submit" value="Signup" class="btn btn-block btn-primary">
      </form>
    </div>
  </div>

</div>

{% endblock %}

{% block bottom_script %}
<script>

</script>
{% endblock %}

src/articles/templates/articles/article_detail.html
{% extends 'base.html' %}

{% block body %}
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-4">{{article.title}}</h1>
    <div class="text-center">
      <img src="{{article.thumb.url}}" alt="" class="img-fluid" style="width: 80%;height:60%">
    </div>
    <p class="lead">{{article.body}}</p>
    <div class="badge badge-secondary float-right">{{article.date}}</div>
  </div>
</div>
{% endblock %}

src/articles/templates/articles/article_list.html
{% extends 'base.html'%}
{% block body %}
<div class="container">
  <h1>Article List</h1>
  {% for article in articles %}
  <div class="card mt-3">
    <div class="card-header text-center display-4">
      {{article.title}}
    </div>
    <div class="card-body">
      <div class="text-center">
        <img src="{{article.thumb.url}}" alt="" class="img-fluid" style="width: 80%;height:60%">
      </div>

      <p>{{article.snippet}}...</p>
      <p>{{article.date}}</p>
      <a href="{% url '_articles:detail' slug=article.slug %}" class="btn btn-primary btn-block">Go to Post</a>
    </div>
  </div>
  {% endfor %}
</div>

{% endblock %}

src/articles/templates/base.html
{% load static%}
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
    integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <!-- customize css -->
  <link rel="stylesheet" href="/static/common/style.css">
  <title>Blog</title>
</head>

<body>
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item active" aria-current="page"><a href="{% url '_articles:list' %}">Home</a></li>
    </ol>
  </nav>
  {% block body %}
  {% endblock %}

  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
    integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
    integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
    integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    crossorigin="anonymous"></script>

  {% block bottom_script %}{% endblock %}
</body>

</html>